title: SE 100 Exercise
author: Eito YONEYAMA
copyright: "2025"
logo: _images/logo.png

execute:
  execute_notebooks: force
  timeout: -1

latex:
  latex_documents:
    targetname: book.tex

# bibtex_bibfiles:
#   - references.bib

repository:
  url: https://github.com/rice8y/se100
  # path_to_book: docs  
  branch: main

html:
  # favicon                   : "_images/icon.png"  
  use_edit_page_button      : true 
  use_repository_button     : true  
  use_issues_button         : true  
  home_page_in_navbar       : true
  extra_navbar              : |
        <div>
        Powered by <a href="https://jupyterbook.org">Jupyter Book</a>
        </div>
        
  baseurl                   : https://rice8y.github.io/se100/
  extra_footer: |
        <div>
        <script src="https://utteranc.es/client.js"
        repo="rice8y/se100"
        issue-term="title"
        label="💬"
        theme="github-light"
        crossorigin="anonymous"
        async>
        </script>
        </div>

launch_buttons:
  notebook_interface: jupyterlab
  colab_url: https://colab.research.google.com

sphinx:
  config:
    language: unknown
    bibtex_reference_style: author_year
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    suppress_warnings:
      ["mystnb.unknown_mime_type", "myst.domains", "mystnb.mime_priority"]
    copybutton_prompt_text: "$"
    intersphinx_mapping:
      ebp:
        - "https://executablebooks.org/en/latest/"
        - null
      myst-parser:
        - "https://myst-parser.readthedocs.io/en/latest/"
        - null
      myst-nb:
        - "https://myst-nb.readthedocs.io/en/latest/"
        - null
      sphinx:
        - "https://www.sphinx-doc.org/en/master"
        - null
      nbformat:
        - "https://nbformat.readthedocs.io/en/latest"
        - null
      sd:
        - https://sphinx-design.readthedocs.io/en/latest
        - null

  extra_extensions:
    - sphinx_inline_tabs
    - sphinx_proof

parse:
   myst_url_schemes: [mailto, http, https]